/**
 * Git operations: clone, branch, checkpoint, diff, commit, push.
 */

import { spawnSync } from "child_process";
import { mkdtempSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { tmpdir } from "os";
import { join, dirname } from "path";
import type { FileChange } from "../agents/types.js";

function run(cmd: string, cwd: string): { stdout: string; stderr: string; code: number } {
  const r = spawnSync(cmd, { shell: true, cwd, encoding: "utf-8" });
  return { stdout: r.stdout ?? "", stderr: r.stderr ?? "", code: r.status ?? 1 };
}

export function cloneRepo(owner: string, repo: string, pat: string): string {
  const dir = mkdtempSync(join(tmpdir(), `orch-${repo}-`));
  const url = `https://x-access-token:${pat}@github.com/${owner}/${repo}.git`;
  const r = run(`git clone "${url}" .`, dir);
  if (r.code !== 0) throw new Error(`Clone failed: ${r.stderr}`);
  run('git config user.email "orchestrator-bot@github-actions"', dir);
  run('git config user.name "Orchestrator Bot"', dir);
  return dir;
}

export function createBranch(cwd: string, branchName: string): void {
  const r = run(`git checkout -b "${branchName}"`, cwd);
  if (r.code !== 0) throw new Error(`Branch creation failed: ${r.stderr}`);
}

export function install(cwd: string, cmd: string): void {
  console.log(`Running: ${cmd}`);
  run(cmd, cwd);
}

/** Write files to disk */
export function applyFiles(cwd: string, files: FileChange[]): void {
  for (const { path, content } of files) {
    const fullPath = join(cwd, path);
    const dir = dirname(fullPath);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(fullPath, content, "utf-8");
    console.log(`  wrote: ${path}`);
  }
}

/** Stage all changes and get the diff (before committing) */
export function getDiff(cwd: string): string {
  run("git add -A", cwd);
  const r = run("git diff --cached", cwd);
  return r.stdout;
}

/** Commit a checkpoint (so we can diff against it later) */
export function checkpoint(cwd: string, message: string): void {
  run("git add -A", cwd);
  run(`git commit -m "${message}" --allow-empty`, cwd);
}

/** Get diff between last two commits (what the previous iteration changed) */
export function diffSinceLastCommit(cwd: string): string {
  const r = run("git diff HEAD~1 HEAD 2>/dev/null || git diff", cwd);
  return r.stdout;
}

export function commitAndPush(cwd: string, branchName: string, issueNumber: number): void {
  run("git add -A", cwd);
  const msg = `feat: auto-implement issue #${issueNumber} via TDD\n\nCloses #${issueNumber}\n\nGenerated by github-orchestrator`;
  run(`git commit -m "${msg.replace(/"/g, '\\"')}" --allow-empty`, cwd);
  const r = run(`git push origin "${branchName}"`, cwd);
  if (r.code !== 0) throw new Error(`Push failed: ${r.stderr}`);
}

export function getRepoFileTree(cwd: string): string {
  const r = run(
    "find . -type f \\( -name '*.ts' -o -name '*.tsx' -o -name '*.js' -o -name '*.jsx' \\) " +
    "| grep -v node_modules | grep -v .next | grep -v dist | grep -v .git | sort | head -60",
    cwd
  );
  return r.stdout.trim();
}

export function getExistingTestSamples(cwd: string, language: string): string {
  const ext = language === "typescript" ? "ts" : "js";
  const r = run(
    `find . -type f \\( -name "*.test.${ext}" -o -name "*.spec.${ext}" \\) ` +
    `| grep -v node_modules | head -3`,
    cwd
  );
  const files = r.stdout.trim().split("\n").filter(Boolean);
  if (files.length === 0) return "No existing test files found.";

  return files
    .map((f) => {
      try {
        const { readFileSync } = require("fs");
        const content = readFileSync(join(cwd, f), "utf-8") as string;
        return `// ${f}\n${content.slice(0, 1200)}`;
      } catch {
        return "";
      }
    })
    .filter(Boolean)
    .join("\n\n---\n\n");
}
