/**
 * create-pr.ts
 *
 * Creates a PR in the target repo from the auto-impl branch.
 * Also updates the original issue with a comment linking to the PR.
 *
 * Usage:
 *   CROSS_REPO_PAT=... tsx scripts/create-pr.ts \
 *     --owner=myorg --repo=myrepo --issue=42 \
 *     --branch=auto-impl/issue-42 --tests-passed=true
 */

import { Octokit } from "@octokit/rest";
import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));

const args = Object.fromEntries(
  process.argv.slice(2).map((a) => {
    const [k, ...v] = a.replace(/^--/, "").split("=");
    return [k, v.join("=")];
  })
);

const OWNER = args["owner"] ?? process.env.ISSUE_OWNER;
const REPO = args["repo"] ?? process.env.ISSUE_REPO;
const ISSUE_NUMBER = Number(args["issue"] ?? process.env.ISSUE_NUMBER);
const BRANCH = args["branch"] ?? process.env.BRANCH_NAME;
const TESTS_PASSED = (args["tests-passed"] ?? process.env.TESTS_PASSED) === "true";
const REVIEW_APPROVED = (args["review-approved"] ?? process.env.REVIEW_APPROVED) === "true";
const TOTAL_COST = args["total-cost"] ?? process.env.TOTAL_COST ?? "N/A";

if (!OWNER || !REPO || !ISSUE_NUMBER || !BRANCH) {
  console.error("Missing required: --owner, --repo, --issue, --branch");
  process.exit(1);
}

const PAT = process.env.CROSS_REPO_PAT;
if (!PAT) throw new Error("CROSS_REPO_PAT is required");

const octokit = new Octokit({ auth: PAT });

// Read config for labels
interface Config {
  repos: unknown[];
  triggerLabel: string;
  wipLabel: string;
  doneLabel: string;
}
const config: Config = JSON.parse(
  readFileSync(join(__dirname, "../configs/target-repos.json"), "utf-8")
);

// Get issue details
const { data: issue } = await octokit.issues.get({
  owner: OWNER,
  repo: REPO,
  issue_number: ISSUE_NUMBER,
});

const testStatus = TESTS_PASSED
  ? "✅ All tests passed"
  : "⚠️ Tests did not pass — please review and fix manually";

const reviewStatus = REVIEW_APPROVED
  ? "✅ AI review approved"
  : "⚠️ AI review flagged issues — see summary";

const prBody = `## Auto-implementation via TDD

**Closes #${ISSUE_NUMBER}**

| | |
|---|---|
| **Tests** | ${testStatus} |
| **AI Review** | ${reviewStatus} |
| **Total AI cost** | $${TOTAL_COST} |

### Pipeline
Generated by [github-orchestrator](https://github.com/${process.env.ORCHESTRATOR_REPO ?? "YOUR_USERNAME/github-orchestrator"}):

1. **Planner** — analyzed issue, created implementation plan
2. **Test Writer** — wrote failing tests (TDD RED phase)
3. **Implementer** — wrote minimal implementation (TDD GREEN phase)
4. **Healer** — self-healing loop (up to 3 iterations) with failure diff context
5. **Reviewer** — final verification against acceptance criteria

### Review Checklist
- [ ] Tests accurately describe the expected behavior
- [ ] Implementation is correct and complete
- [ ] No unintended side effects
- [ ] Code follows project conventions

---
*Generated automatically. Please review carefully before merging.*`;

// Get default branch
const { data: repoData } = await octokit.repos.get({ owner: OWNER, repo: REPO });
const defaultBranch = repoData.default_branch;

// Create PR
console.log(`Creating PR: ${BRANCH} → ${defaultBranch}`);
const { data: pr } = await octokit.pulls.create({
  owner: OWNER,
  repo: REPO,
  title: `feat: auto-implement issue #${ISSUE_NUMBER} - ${issue.title}`,
  body: prBody,
  head: BRANCH,
  base: defaultBranch,
  draft: !TESTS_PASSED, // Draft if tests didn't pass
});

console.log(`PR created: ${pr.html_url}`);

// Comment on the original issue
await octokit.issues.createComment({
  owner: OWNER,
  repo: REPO,
  issue_number: ISSUE_NUMBER,
  body: `🤖 **Auto-implementation PR created**\n\n${testStatus}\n\nPR: ${pr.html_url}`,
});

// Update labels: remove wip, add done
await octokit.issues.removeLabel({
  owner: OWNER,
  repo: REPO,
  issue_number: ISSUE_NUMBER,
  name: config.wipLabel,
}).catch(() => {}); // OK if label not present

await octokit.issues.addLabels({
  owner: OWNER,
  repo: REPO,
  issue_number: ISSUE_NUMBER,
  labels: [config.doneLabel],
});

console.log(`Issue #${ISSUE_NUMBER} updated with label "${config.doneLabel}"`);

// Output PR URL
if (process.env.GITHUB_OUTPUT) {
  const { appendFileSync } = await import("fs");
  appendFileSync(process.env.GITHUB_OUTPUT, `pr_url=${pr.html_url}\n`);
} else {
  console.log(`\nPR URL: ${pr.html_url}`);
}
